# Plugins
whitelist: []
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

# Conversion
excerpt_separator: "<!--content-->"

# Setup
title: makingmusic.lv
description: Musical blog
url: http://makingmusic.lv
baseurl: /

# For jekyl-feed
name: makingmusic.lv
author:
  name: Irina Hagenbo
  email: irina.kozjura@gmail.com
  uri: http://makingmusic.lv
